services:
  services-plugins-tensorify-io:
    build:
      context: ../../
      dockerfile: services/plugins.tensorify.io/Dockerfile
    ports:
      - "3004:3004"
    restart: unless-stopped
    env_file:
      - .env
